Existing bugs
ladybirdweb/faveo-helpdesk pull request #8068
Opened 2023-03-07 12:08 UTC by Noor-mommadhi

ISSUES FIXES: #7916

1)Issue 9:For each ticket, the Ticket conversion/description is shown twice.

2)Issue 15:Data is not vanishing on create organization page. click on create, input the data to the organization name, and click on close

3)Issue 47:While adding the language for the ISO-CODE, throwing the wrong alert message for the number of characters.

4)Issue 48:In cron settings, click on the link redirecting to a blank page.

5)Issue 51: In the knowledge base setting textbox. Suppose we don’t input the data to the required field and submit it. By default, it's picking the value as ‘0’.

6)Issue 20:No option available to remove the due date in ticket creation.

7)Issue 10:By default ticket due date is picked as the ticket created date. (if the ticket due date is selected on a different date. But, still picked the same date.

2023-03-09 09:39 UTC, sowmiyasubramaniyan approved these changes

2023-03-13 09:19 UTC, DhanyaChengappa commented on app/Http/Controllers/Agent/helpdesk/TicketController.php
> +        //  return '';
remove this line if not required

2023-03-13 10:51 UTC, RafficMohammed requested changes
@Noor-mommadhi U added too many unwanted files. Please remove it

2023-03-13 13:21 UTC, SarfrazS requested changes
Issue 1:- while adding language with valid inputs getting below error, but language added.
![image](https://user-images.githubusercontent.com/18435376/224713718-10fe4c1e-ee96-41a2-acd2-449eefb8b7d0.png)
![image](https://user-images.githubusercontent.com/18435376/224713934-5170484b-292a-4022-9cda-335ea2605762.png)

Rest all the below issues are fixed and working fine.
1)Issue 9:For each ticket, the Ticket conversion/description is shown twice.

2)Issue 15:Data is not vanishing on create organization page. click on create, input the data to the organization name, and click on close

3)Issue 47:While adding the language for the ISO-CODE, throwing the wrong alert message for the number of characters.

4)Issue 48:In cron settings, click on the link redirecting to a blank page.

5)Issue 51: In the knowledge base setting textbox. Suppose we don’t input the data to the required field and submit it. By default, it's picking the value as ‘0’.

6)Issue 20:No option available to remove the due date in ticket creation.

7)Issue 10:By default ticket due date is picked as the ticket created date. (if the ticket due date is selected on a different date. But, still picked the same date.

2023-03-14 04:59 UTC, Umasri-V commented
found new issues https://docs.google.com/document/d/1LvC-KUd3fTn8OIcxFzcTSpL0D0Qnci5RznFZQr3GeP0/edit

2023-03-17 07:19 UTC, RafficMohammed commented on app/Http/Controllers/Agent/helpdesk/TicketController.php
>      {
add $duedate = null in arguments

2023-03-17 07:19 UTC, RafficMohammed commented on app/Http/Controllers/Agent/helpdesk/TicketController.php
> +    public function check_ticket($user_id, $subject, $body, $helptopic, $sla, $priority, $source, $headers, $dept, $assignto, $form_data, $status, $duedate)
Here too

2023-03-17 07:20 UTC, RafficMohammed commented on app/Http/Controllers/Agent/helpdesk/TicketController.php
> +    public function createTicket($user_id, $subject, $body, $helptopic, $sla, $priority, $source, $headers, $dept, $assignto, $form_data, $status, $duedate)
Here too

2023-03-17 07:20 UTC, Sakthi002 commented
> @Noor-mommadhi U added too many unwanted files. Please remove it

Auto Generated files sir

2023-03-17 07:20 UTC, RafficMohammed commented on app/Http/Controllers/Agent/helpdesk/TicketController.php
> +            $duedate_datetime = \DateTime::createFromFormat('d/m/Y', $duedate);
U can use Carbon facades instead of Datetime. Why are u using this ?

2023-03-17 07:25 UTC, RafficMohammed commented
@Noor-mommadhi When you r adding any new argument, you must be very careful. @SarfrazS Check ticket fetch functionality here

2023-03-22 10:17 UTC, SarfrazS approved these changes
Pointed issues are fixed.

2023-03-26 16:58 UTC, RafficMohammed approved these changes

2023-03-26 16:59 UTC, RafficMohammed commented
@Noor-mommadhi Squash commits

2023-03-29 04:46 UTC, merged