#8114-fix
ladybirdweb/faveo-helpdesk pull request #8116
Opened 2023-03-20 11:32 UTC by Noor-mommadhi

fixes #8114

2023-03-22 10:29 UTC, SarfrazS requested changes
We we click on register button still getting same error.
![image](https://user-images.githubusercontent.com/18435376/226875693-2195b848-6e43-4843-b03a-cede7a143f27.png)

2023-03-23 05:17 UTC, sowmiyasubramaniyan approved these changes

2023-03-25 05:53 UTC, SarfrazS approved these changes
Pointed issues are fixed. Now working fine.

2023-03-26 17:05 UTC, RafficMohammed commented
@Noor-mommadhi Squash commits

2023-03-29 04:47 UTC, merged