xss-injection
ladybirdweb/faveo-helpdesk pull request #8171
Opened 2023-05-02 05:41 UTC by Noor-mommadhi

Fixes -#8163 
https://huntr.dev/bounties/7f87c6ba-a4ec-4836-a044-ef5f90b018af/?token=af078dd65ad3872b310ccff731f5969f95c1ee3a5da38b0a5d001c7434fb94de81c26919b8900d27fb962feaac7e01cbdb19082e7f91f7b72a39dcfa04854d8da32d621784c4abb4961046d923abc0c7cb1ffd5ea82e1319797333bc3c483a96540de5f11880e4e3ea11e70cd4c46504b7a46522b325458c021e07df1e1d

2023-05-05 07:25 UTC, sowmiyasubramaniyan approved these changes

2023-05-12 11:31 UTC, RafficMohammed approved these changes

2023-05-23 07:37 UTC, Sabaric12 approved these changes
While Testing this pr with existing installation 
While checking that profile page we can able to change the profile details and we are getting the successful message 
But in this profile picture page phone number text fields is accepting string in community all the places it is happening in master branch also I asked with developer about this she said she need to create seperate document for happening in all the places like in admin panel the user directory field etc all the places where ever it is reflected
![Screenshot from 2023-05-23 13-06-47](https://github.com/ladybirdweb/faveo-helpdesk/assets/118339159/497a63c3-6469-4cc1-a78f-bfa6149b025d)

2023-05-25 17:48 UTC, SarfrazS requested changes
On the user data table phone extension not showing. Is it correct?
![image](https://github.com/ladybirdweb/faveo-helpdesk/assets/18435376/75d63d52-2e67-405f-9417-7c1206096e0f)
![image](https://github.com/ladybirdweb/faveo-helpdesk/assets/18435376/f5bcd54b-4199-4a56-897a-62db1f356c4f)
![image](https://github.com/ladybirdweb/faveo-helpdesk/assets/18435376/cca904ca-4e92-4797-85b0-4c8d036a55b0)

Note:- As per the developer I checked value not showing on the user data table.

2023-05-26 06:19 UTC, SarfrazS approved these changes
Before showing html in mobile now it not showing
![image](https://github.com/ladybirdweb/faveo-helpdesk/assets/18435376/91e52e1d-2f43-46eb-b7d6-ac5cf6942204)

Note:- For phone extension we are creating separate issue. Now i m approving this pr.

2023-06-08 13:25 UTC, merged