Mail controller controller fix.
ladybirdweb/faveo-helpdesk pull request #8203
Opened 2023-06-18 08:32 UTC by mucan54

Whenever we want to use mail providers like sendgrid we need to use different username then mail address. So this functionality is needed and added.

2023-06-19 06:37 UTC, RafficMohammed approved these changes

2023-06-19 11:38 UTC, RafficMohammed commented on app/Http/Controllers/Common/PhpMailController.php
> +                    'from_mail'   => $mail->email_address,
remove from_mail attribute here

2023-06-19 11:39 UTC, RafficMohammed requested changes
@mucan54  If u want to use sendgrid email service provider, u can add it like How we added for Mailgun.

2023-06-19 18:57 UTC, mucan54 commented
> @mucan54 If u want to use sendgrid email service provider, u can add it like How we added for Mailgun.

In fact I gice only one example, my development doesnt blocks current worflow it adds more functionality since the username is not required user can leave it empty to use email as username or pick a different username to login

2023-08-28 06:16 UTC, Noor-mommadhi commented
The updated PR is  #8210

2023-08-28 06:16 UTC, closed without merging