Ticket time issues fixed
ladybirdweb/faveo-helpdesk pull request #8219
Opened 2023-09-06 09:12 UTC by KNaveenraj-ladybird

Fixes -#8213

2023-09-08 04:14 UTC, Sabaric12 commented
@KNaveenraj-ladybird Get the code approval for this PR

2023-09-11 09:30 UTC, ajaz-ul-haq submitted a review, later dismissed

2023-09-11 10:22 UTC, RafficMohammed commented on app/Http/Controllers/Agent/helpdesk/TicketController.php
> +        $result = ['success' => 'Replied successfully'];
Use trans() or Lang::get();

2023-09-11 10:24 UTC, RafficMohammed requested changes
Write a test cases for these changes

2023-09-13 05:54 UTC, DhanyaChengappa requested changes

2023-09-13 05:54 UTC, DhanyaChengappa commented on resources/views/themes/default1/agent/helpdesk/ticket/timeline.blade.php
> +                //$('html, body').animate({ scrollTop: $("#inboxactions").offset().top }, 500);
if this line is not required, lets remove

2023-09-27 12:57 UTC, RafficMohammed approved these changes

2023-09-29 16:42 UTC, ajaz-ul-haq approved these changes

2023-10-03 07:17 UTC, Sabaric12 commented
Tested this PR with the fresh installation
Issue 1:
While replying to the ticket created by the user replied agent or admin the success alert message is coming but it vanishes suddenly
![image](https://github.com/ladybirdweb/faveo-helpdesk/assets/118339159/10d4b461-6d9a-4014-8773-0d21905cb2ba)
@KNaveenraj-ladybird resolve the conflicts also
Round 1 Testing Summary:
Total time in days: 3 hours
Total issues: 1
Minor - 0 
Major - 1
Critical - 0
No of times PR was sent for Functionality correction: 1
PR breaks existing functionality: No

2023-10-04 06:06 UTC, Sabaric12 commented
Today's task:-
Tested this PR with the fresh installation
The mentioned issues are working fine and one separate issue has been created
https://github.com/ladybirdweb/faveo-helpdesk/issues/8235
Round 1 Testing Summary:
Total time in days: 3 hours
Total issues: 0
Minor - 0 
Major - 0
Critical - 0
No of times PR was sent for Functionality correction: 0
PR breaks existing functionality: No

2023-10-04 06:07 UTC, Sabaric12 approved these changes

2023-10-04 12:50 UTC, AbishekChinnaraju approved these changes

2023-10-26 08:03 UTC, merged

2023-10-26 09:35 UTC, KNaveenraj-ladybird commented
Hello ladybirdweb/faveo-helpdeskThank you for contacting us. This is an automated response confirming the receipt of your ticket. Our team will get back to you as soon as possible. When replying, please make sure that the ticket ID is kept in the subject so that we can track your replies.Ticket ID: AAAA-0000-0002  You can check the status of or update this ticket online at: https://localhost/faveo-helpdesk/public/check_ticket/eyJpdiI6InRTQmtpL1hBb0QrQTA4NDhGL1Q3Z0E9PSIsInZhbHVlIjoiM1dwUDBHZkFzNld5dXI5aSt6a2htUT09IiwibWFjIjoiOGZjNjBiOTdlY2M0ZGE0Y2ZkZjQxMjk1ODFjMDY3MTcyNWZkY2RjY2Q1MjFiMDYxZGY5NGVkYTBiYWIwNWY2ZiIsInRhZyI6IiJ9

2023-10-26 09:37 UTC, KNaveenraj-ladybird commented
---Reply above this line--- Hello ***@***.***,A reply been made to ticket AAAA-0000-0002FromName: NaveenrajE-mail: ***@***.*** Hello Naveenraj,New ticket AAAA-0000-0002created FromName: ladybirdweb/faveo-helpdesk   E-mail: ***@***.*** 
Merged #8219 into development.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/ladybirdweb/faveo-helpdesk/pull/8219#event-10776252602",
"url": "https://github.com/ladybirdweb/faveo-helpdesk/pull/8219#event-10776252602",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]Kind Regards, Support Center
Kind Regards, Support Center