change_status_fix
ladybirdweb/faveo-helpdesk pull request #8224
Opened 2023-09-13 07:35 UTC by Noor-mommadhi

Fixes -#8180

2023-09-13 13:16 UTC, RafficMohammed commented on routes/web.php
> +        Route::post('select_all', [Agent\helpdesk\TicketController::class, 'select_all'])->name('select_all');
use proper route name like select/all

2023-09-13 13:16 UTC, RafficMohammed requested changes

2023-09-13 13:16 UTC, RafficMohammed commented on resources/views/themes/default1/client/helpdesk/ckeckticket.blade.php
>  @extends('themes.default1.client.layout.client')
Write a test cases for this P.R

2023-09-14 07:00 UTC, DhanyaChengappa commented
- [ ] Add a confirmation pop-up before status change to close

2023-09-20 09:21 UTC, Noor-mommadhi commented
@DhanyaChengappa please create a separate issue for "Add a confirmation pop-up before status change to close"

2023-09-22 07:47 UTC, Sabaric12 commented
@Noor-mommadhi get demo approved and code approved for this PR

2023-10-05 04:09 UTC, Sabaric12 commented
@Noor-mommadhi resolve the conflicts

2023-10-10 05:10 UTC, RafficMohammed approved these changes

2023-10-13 08:22 UTC, Sabaric12 commented
Round 1: Testing Summary
Tested this PR with the existing installation the mentioned issues are working fine now
Total time in days: 1.5 Hours
Total issues:0
Minor - 0 
Major - 0 
Critical - 0
No of times PR was sent for Functionality correction:0
PR breaks existing functionality: No
Note:-
Separate Issues are created for the pop-up messages
https://github.com/ladybirdweb/faveo-helpdesk/issues/8247

2023-10-13 08:22 UTC, Sabaric12 submitted a review, later dismissed

2023-10-14 04:30 UTC, AbishekChinnaraju commented
**Second Round  Testing Summary :**
Tested this PR with the existing server installation 
Total time in days: 1.5 Hours
Total issues:0
Minor - 0
Major - 0
Critical - 0
No of times PR was sent for Functionality correction:0
PR breaks existing functionality: No
**Note:-**
Separate Issues are created for the pop-up messages
https://github.com/ladybirdweb/faveo-helpdesk/issues/8247

2023-10-14 04:30 UTC, AbishekChinnaraju submitted a review, later dismissed

2023-10-26 09:36 UTC, KNaveenraj-ladybird commented
Hello ladybirdweb/faveo-helpdeskThank you for contacting us. This is an automated response confirming the receipt of your ticket. Our team will get back to you as soon as possible. When replying, please make sure that the ticket ID is kept in the subject so that we can track your replies.Ticket ID: AAAA-0000-0008  You can check the status of or update this ticket online at: https://localhost/faveo-helpdesk/public/check_ticket/eyJpdiI6IkxkV0pQNGZRaW9OZ09IMmtHTlBMVGc9PSIsInZhbHVlIjoiaEQzQXgzMjl1TGJrYzlJai9JWk9xUT09IiwibWFjIjoiYTcwODczY2E4YThkZmI5ZDZjYTAwMDgyMmEyMWQ2MWZiMjc4YjYwYWVjZDFhYzFjNTU3NWQ4MjNhZTI4MzlkNiIsInRhZyI6IiJ9

2023-10-26 09:38 UTC, KNaveenraj-ladybird commented
---Reply above this line--- Hello ***@***.***,A reply been made to ticket AAAA-0000-0008FromName: NaveenrajE-mail: ***@***.*** Hello Naveenraj,New ticket AAAA-0000-0008created FromName: ladybirdweb/faveo-helpdesk   E-mail: ***@***.*** 
Closed #8224.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/ladybirdweb/faveo-helpdesk/pull/8224#event-10776736179",
"url": "https://github.com/ladybirdweb/faveo-helpdesk/pull/8224#event-10776736179",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]Kind Regards, Support Center
Kind Regards, Support Center

2023-10-27 05:14 UTC, merged